### ISSUE TITLE
Add support for editor color scheme

### ISSUE THREAD

**Issue by fabiankaegy** [helen/admin-color-schemer#32]
The color theme in WordPress Core now add custom colors also to the editor. This is being done by adding css custom properties in the editor. These get injected via a body class on the editor pages.

The available colors in the editor seem to be:
```css
--wp-admin-theme-color: #000;
--wp-admin-theme-color-darker-10: #000;
--wp-admin-theme-color-darker-20: #000;
```

In core they are defined here: https://github.com/WordPress/WordPress/blob/ad48a153873cdef28ab03c54a034de807e729052/wp-includes/css/dist/edit-post/style.css#L1998-L2008

```css
body.admin-color-light {
    --wp-admin-theme-color: #0085ba;
    --wp-admin-theme-color-darker-10: #0073a1;
    --wp-admin-theme-color-darker-20: #006187;
    --wp-admin-border-width-focus:2px
}

body.admin-color-modern {
    --wp-admin-theme-color: #3858e9;
    --wp-admin-theme-color-darker-10: #2145e6;
    --wp-admin-theme-color-darker-20: #183ad6;
    --wp-admin-border-width-focus:2px
}

body.admin-color-blue {
    --wp-admin-theme-color: #096484;
    --wp-admin-theme-color-darker-10: #07526c;
    --wp-admin-theme-color-darker-20: #064054;
    --wp-admin-border-width-focus:2px
}

body.admin-color-coffee {
    --wp-admin-theme-color: #46403c;
    --wp-admin-theme-color-darker-10: #383330;
    --wp-admin-theme-color-darker-20: #2b2724;
    --wp-admin-border-width-focus:2px
}

body.admin-color-ectoplasm {
    --wp-admin-theme-color: #523f6d;
    --wp-admin-theme-color-darker-10: #46365d;
    --wp-admin-theme-color-darker-20: #3a2c4d;
    --wp-admin-border-width-focus:2px
}

body.admin-color-midnight {
    --wp-admin-theme-color: #e14d43;
    --wp-admin-theme-color-darker-10: #dd382d;
    --wp-admin-theme-color-darker-20: #d02c21;
    --wp-admin-border-width-focus:2px
}

body.admin-color-ocean {
    --wp-admin-theme-color: #627c83;
    --wp-admin-theme-color-darker-10: #576e74;
    --wp-admin-theme-color-darker-20: #4c6066;
    --wp-admin-border-width-focus:2px
}

body.admin-color-sunrise {
    --wp-admin-theme-color: #dd823b;
    --wp-admin-theme-color-darker-10: #d97426;
    --wp-admin-theme-color-darker-20: #c36922;
    --wp-admin-border-width-focus:2px
}
```
